apiVersion: apps/v1
kind: Deployment
metadata:
  name: jm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jm-frontend
  template:
    metadata:
      labels:
        app: jm-frontend
    spec:
      containers:
      - name: frontend
        image: jm-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jm-frontend
spec:
  selector:
    app: jm-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
